apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
type: Opaque
data:
  DATABASE_URL: {{ .Values.secrets.DATABASE_URL | b64enc }}
  SECRET_KEY: {{ .Values.secrets.SECRET_KEY | b64enc }}
  ALGORITHM: {{ .Values.secrets.ALGORITHM | b64enc }}
  ACCESS_TOKEN_EXPIRE_MINUTES: {{ .Values.secrets.ACCESS_TOKEN_EXPIRE_MINUTES | toString | b64enc }}